// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ3nZjBY6Ux2sUdmZUImx0osSNkVyQlZk',
    appId: '1:271960088054:web:ef2115a87a20ccac5e7bd7',
    messagingSenderId: '271960088054',
    projectId: 'cleandart2login',
    authDomain: 'cleandart2login.firebaseapp.com',
    storageBucket: 'cleandart2login.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwIuplXNSZrMrcHyTdwy-Lmt-Btw7Bl0o',
    appId: '1:271960088054:android:45467543fd7afc665e7bd7',
    messagingSenderId: '271960088054',
    projectId: 'cleandart2login',
    storageBucket: 'cleandart2login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2JvIhhgAzPhm_9yhhb-DuJut9FvX2-a4',
    appId: '1:271960088054:ios:219ee21c8273f9c75e7bd7',
    messagingSenderId: '271960088054',
    projectId: 'cleandart2login',
    storageBucket: 'cleandart2login.appspot.com',
    iosClientId: '271960088054-gcvmffohgkt3a66c7odtu6v3m5vc0oo5.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLoginCleandart2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2JvIhhgAzPhm_9yhhb-DuJut9FvX2-a4',
    appId: '1:271960088054:ios:987824621827d4e25e7bd7',
    messagingSenderId: '271960088054',
    projectId: 'cleandart2login',
    storageBucket: 'cleandart2login.appspot.com',
    iosClientId: '271960088054-ua2akc5mdvfcohb9t4iubg5c7cqibtut.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLoginCleandart2.RunnerTests',
  );
}
